# -*- coding: utf-8 -*-
"""TestML.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1NxuVh7yY3DZbJRCFO999-dVbvSeJvmBn
"""

from google.colab import files
from flask import Flask, request
from keras.preprocessing import image
from keras.models import load_model
import numpy as np
import cv2
import keras
import json
import os
from google.colab import drive
drive.mount('/content/gdrive')

os.environ['KAGGLE_CONFIG_DIR'] = '/content/gdrive/MyDrive/kaggle_dataset'


app = Flask(__name__)

model_json = open(
    '/content/gdrive/MyDrive/kaggle_dataset/model.json', 'r').read()
model = keras.models.model_from_json(model_json)
model.load_weights(
    '/content/gdrive/MyDrive/kaggle_dataset/model-agrostock2.h5')


uploaded = files.upload()

for fn in uploaded.keys():

    # predicting images
    path = fn
    img = image.load_img(path, target_size=(180, 180))

    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    images = np.vstack([x])
    fruit_list = ["Fresh Food", "Fresh Food", "Fresh Food", "Fresh Food", "Fresh Food", "Fresh Food",
                  "Stale Food", "Stale Food", "Stale Food", "Stale Food", "Stale Food", "Stale Food"]

    classes = model.predict(images, batch_size=32)

#	return dic[round(p[0])]

print(fruit_list[np.argmax(classes)])
print('Accuracy:', np.max(classes)*100, '%')

# if __name__ == '__main__':
#	app.run(host='0.0.0.0', port=5000)
